- name: PLAY1
  hosts: local
  connection: local
  tasks: 
    - name: PLAY1 and TASK1
      ansible.builtin.debug:
       msg: "Hellp from play1 and Task1"

- name: PLAY2
  hosts: local
  connection: local
  tasks:
  - name: PLAY2 and TASK1 
    ansible.builtin.debug:
      msg: "Hello from PLAY2 and TASK1"