- name: variables
  hosts: local
  connection: local
  vars: 
    COURSE: "DevOps with AWS"
    DURATION: 30 weeks
    TRAINER: MYSELF

  tasks: 
  - name: print the variables
    ansible.builtin.debug:
      msg: "This is just practice {{ COURSE }} of {{ DURATION }} trained by {{ TRAINER }}"