- name: variables
  hosts: local
  connection: local
  vars_files: #this will take the variables defined in the vars.yaml file
  - vars.yaml

  tasks: 
  - name: print the variables
    vars: #task level varibles and task level variables can override play level variables
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "This is just practice {{ COURSE }} of {{ DURATION }} trained by {{ TRAINER }}"

  - name: print the variables
    ansible.builtin.debug:
      msg: "This is just practice {{ COURSE }} of {{ DURATION }} trained by {{ TRAINER }}"