- name: Devops course
  hosts: local
  connection: local 
  vars:
    course_name: "Devops with aws"
    duration: 120
    topics: 
    - linux
    - shell
    - ansible
    - AWS
    live: true
    tools:
      ci: jenkins
      cloud: aws
      containerization: docker
  tasks: 
  - name: print course information
    ansible.builtin.debug:
      msg: " Hello Iam learning {{ course_name }}, duration {{ duration }}, topics are: {{ topics }}, is it {{ live }}, tools covered are: {{ tools }}"