- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loop: 
    - This is first
    - This is second 
    - This is third 
#Installing packages in using ansible loops 
  - name: install packages
    become: yes
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - mysql
    - git

#accessing the loops in different way 
  - name: install or delete packages
    become: yes 
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: zip, state: 'absent'}
    - { name: mysql, state: 'present'}