- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loop: 
    - This is first
    - This is second 
    - This is third 
#Installing packages in using ansible loops 
   - name: install packages
     ansible.builtin.package:
      name: "{{ item }}"
      state: installed
     loop:
     - mysql
     - git